# Generated by Django 3.0.6 on 2020-05-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('small_description', models.CharField(max_length=70)),
                ('detailed_description', models.CharField(max_length=500)),
                ('code_link', models.URLField()),
                ('picture1', models.ImageField(upload_to='')),
                ('picture2', models.ImageField(upload_to='')),
                ('picture3', models.ImageField(upload_to='')),
            ],
        ),
    ]
